package com.hackathon.backendorange.exception;

public class ProjectIdNotFoundException extends RuntimeException{

    public ProjectIdNotFoundException(){
        super("O projeto n√£o foi encontrado!");
    }
}
